WebApplication3HtmlHelperClasses/Models/ErrorViewModel.cs
namespace WebApplication3HtmlHelperClasses.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication3HtmlHelperClasses/Models/Student.cs
using System.ComponentModel;

namespace WebApplication3HtmlHelperClasses.Models
{
    public class Student
    {
        [DisplayName("Student Id")]
        public int Id { get; set; }
        [DisplayName("Enter Full Name")]
        public string Name { get; set; }
        public string Address { get; set; }

        [DisplayName("Date of Birth")]
        public DateOnly Dob { get; set; }
        public string Email { get; set; }
    }
}

WebApplication3HtmlHelperClasses/Controllers/CustomeHelperController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication3HtmlHelperClasses.Controllers
{
    public class CustomeHelperController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplication3HtmlHelperClasses/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplication3HtmlHelperClasses.Models;

namespace WebApplication3HtmlHelperClasses.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public string SendData(string uname, string password)
        {
            return $"data got {uname}, {password}";
        }

        public IActionResult SignUp()
        {
            return View();
        }

        public IActionResult showSignupData(IFormCollection data)
        {

            return View("Index");
        }
    }
}

WebApplication3HtmlHelperClasses/Controllers/StronglyTypedHelperController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication3HtmlHelperClasses.Controllers
{
    public class StronglyTypedHelperController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public string SignUp(int Id, string Name, string Address)
        {
            return Id + "-" + Name + "-" + Address; 
        }
    }
}

WebApplication3HtmlHelperClasses/Controllers/TemplatedHelperController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using WebApplication3HtmlHelperClasses.Models;

namespace WebApplication3HtmlHelperClasses.Controllers
{
    public class TemplatedHelperController : Controller
    {
       
        public IActionResult Index()
        {
            Student student = new Student();
            return View(student);
        }

        public string SignUp()
        {
            string id = Request.Form["Id"];
            string name = Request.Form["Name"];
            return id + " " + name;
        }
    }
}

WebApplication3HtmlHelperClasses/Views/CustomeHelper/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h2>welcome to custom helper</h2>

<div>
    @MyHelper.Button("submit", "Register")
    @MyHelper.Button("reset", "Reset")
    @MyHelper.Image("/images/1.png", "images", "300px")
</div>

WebApplication3HtmlHelperClasses/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<h2>Login</h2>

@using(Html.BeginForm("SendData", "Home"))
{
    @Html.Label("uname", "Enter User Name", new {@class="form-label"})
    @Html.TextBox("uname", "", new {@class="form-control"})
    <br/>
    @Html.Label("password", "Enter Name", new { @class = "form-label" })
    @Html.TextBox("password", "", new { @class = "form-control" })

    <br />
    <button type="submit" >Submit </button>

    <div>
      Not Registered?  @Html.ActionLink("Click here to Register", "SignUp", "Home")
    </div>
}

WebApplication3HtmlHelperClasses/Views/Home/SignUp.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    List<string> crs = new List<string> { "dotnet", "CPP", "Python", "Azure", "Devops" };
}
<h2>Register</h2>
@using(Html.BeginForm("showSignupData", "Home"))
{
    
    @Html.Label("fullName", "Enter Full Name", new {@class="form-label"})
    @Html.TextBox("fullName", "", new {@class="form-control"})
    <br />
    <div>
        @Html.Label("userName", "Enter User Name", new { @class = "form-label" })
        @Html.TextBox("userName", "", new { @class = "form-control" })
    </div>

    <div>
        @Html.Label("password", "Enter password", new { @class = "form-label" })
        @Html.Password("password", "", new { @class = "form-control" })
    </div>
    <div>
        @Html.Label("rePassword", "Confirm password", new { @class = "form-label" })
        @Html.Password("rePassword", "", new { @class = "form-control" })
    </div>
    @Html.Label("age", "Enter Age", new { @class = "form-label" })
    @Html.TextBox("age", "", new { @class = "form-control" })
    <br />

    @Html.Label("gender", "Select Gender", new { @class = "form-label" })
    <div>
        @Html.RadioButton("gender", "male", true, new { @id = "male", @class = "form-Control" }) Male
    </div>
    <div>
        @Html.RadioButton("gender", "female", false, new { @id = "female", @class = "form-Control" }) Female
    </div>
    <div>
        @Html.RadioButton("gender", "other", false, new { @id = "other", @class = "form-Control" }) Other
    </div>

    <br />

    <div>
        @Html.Label("course", "Courses", new {@class="form-label"})
        @Html.DropDownList("course", new SelectList(crs), "--select course--");
    </div>

    <div>
        <input type="submit" value="Register" class="btn btn-success"/> 
        <input type="reset" value="Reset" class="btn btn-danger" />
    </div>

    <div>
        If aleredy registered @Html.ActionLink("Click here to login", "Index", "Home")
    </div>
}

WebApplication3HtmlHelperClasses/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3HtmlHelperClasses</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3HtmlHelperClasses.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3HtmlHelperClasses</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebApplication3HtmlHelperClasses - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication3HtmlHelperClasses/Views/StronglyTypedHelper/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Student

<h2>Strongly typed Helper class</h2>

@using(Html.BeginForm("SignUp", "StronglyTypedHelper"))
{
    @Html.LabelFor(x=> x.Id)
    @Html.TextBoxFor(x=> x.Id)
    <br />

    @Html.LabelFor(x=> x.Name)
    @Html.TextBoxFor(x=> x.Name)
    <br />

    @Html.LabelFor(x=> x.Address)
    @Html.TextAreaFor(x=> x.Address)
    <br />

    <input type="submit" value="submit" />
}

WebApplication3HtmlHelperClasses/Views/TemplatedHelper/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Student
<h2>Student Registration</h2>

@using (Html.BeginForm("SignUp", "TemplatedHelper"))
{
    @Html.DisplayName("Id")
    @Html.Editor("Id")
    <br />

    @Html.DisplayName("Name")
    @Html.Editor("Name")
    <br />

    @Html.DisplayName("Email")
    @Html.Editor("Email")
    <br />

    @Html.DisplayName("Dob")
    @Html.Editor("Dob")
    <br />

    @Html.DisplayName("Address")
    @Html.Editor("Address")
    <br />

    <input type="submit" value="submit" />
}